# Generated by Django 5.2 on 2025-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Dato Generado',
                'verbose_name_plural': 'Datos Generados',
                'db_table': 'tb_generated',
                'ordering': ['-data_created', 'id'],
            },
        ),
    ]
