# Generated by Django 5.2 on 2025-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbgenerated',
            options={'ordering': ['-data_created', 'id'], 'verbose_name': 'Registro Generado', 'verbose_name_plural': 'Registros Generados'},
        ),
        migrations.AddField(
            model_name='tbgenerated',
            name='data_string',
            field=models.CharField(default='', help_text='La cadena de datos generada (máx 11 caracteres).', max_length=11, verbose_name='Información Guardada'),
            preserve_default=False,
        ),
    ]
